// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	GetPost(ctx context.Context, slug string) (Post, error)
	InsertPost(ctx context.Context, arg InsertPostParams) (Post, error)
	ListPosts(ctx context.Context) ([]Post, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
